Importing The Needed Libraries


In [63]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Load The Dataset

In [64]:
dataset = pd.read_csv('/content/sleep_productivity.csv')
x = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values
y = y.reshape(len(y),1)


In [65]:
print(x)

[[  7.6 189.    2.3  59.    7.3]
 [  6.8 174.    4.3  59.    7.7]
 [  7.8  50.    2.6  59.    6.6]
 [  8.8  54.    3.6  44.    8.6]
 [  6.7 243.    3.7  40.    6.9]
 [  6.7 130.    1.9  28.    8.5]
 [  8.9 134.    5.8  14.    8.1]
 [  7.9  20.    4.9  44.    5.7]
 [  6.4 166.    5.7   0.    3.6]
 [  7.7 273.    5.5  24.    5.2]
 [  6.4  88.    4.    6.    7. ]
 [  6.4  13.    5.6   8.    7. ]
 [  7.3 241.    1.4  23.    6.5]
 [  4.7 264.    2.    0.    4.6]
 [  4.9  52.    1.2  43.    6.4]
 [  6.3  91.    2.6   7.    5.3]
 [  5.8 263.    2.9  23.    8.8]
 [  7.4  34.    2.4  10.    8.1]
 [  5.9 205.    5.1  50.    7.3]
 [  5.3  80.    2.8  16.    4.4]]


In [66]:
print(y)

[[5.6]
 [7.1]
 [5.8]
 [6.7]
 [5.4]
 [4.6]
 [8. ]
 [8.4]
 [5.6]
 [5.7]
 [3.1]
 [5.7]
 [3.7]
 [2.3]
 [4.4]
 [4. ]
 [2.1]
 [4.6]
 [6.4]
 [3.2]]


Data Exploration


Train Test Split

In [67]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [68]:
print(x_train)

[[  7.8  50.    2.6  59.    6.6]
 [  4.9  52.    1.2  43.    6.4]
 [  6.7 243.    3.7  40.    6.9]
 [  7.4  34.    2.4  10.    8.1]
 [  7.9  20.    4.9  44.    5.7]
 [  6.8 174.    4.3  59.    7.7]
 [  4.7 264.    2.    0.    4.6]
 [  7.6 189.    2.3  59.    7.3]
 [  5.3  80.    2.8  16.    4.4]
 [  5.9 205.    5.1  50.    7.3]
 [  7.7 273.    5.5  24.    5.2]
 [  6.3  91.    2.6   7.    5.3]
 [  6.4 166.    5.7   0.    3.6]
 [  7.3 241.    1.4  23.    6.5]
 [  6.4  13.    5.6   8.    7. ]
 [  6.7 130.    1.9  28.    8.5]]


In [69]:
print(x_test)

[[  8.8  54.    3.6  44.    8.6]
 [  5.8 263.    2.9  23.    8.8]
 [  8.9 134.    5.8  14.    8.1]
 [  6.4  88.    4.    6.    7. ]]


In [70]:
print(y_train)

[[5.8]
 [4.4]
 [5.4]
 [4.6]
 [8.4]
 [7.1]
 [2.3]
 [5.6]
 [3.2]
 [6.4]
 [5.7]
 [4. ]
 [5.6]
 [3.7]
 [5.7]
 [4.6]]


In [71]:
print(y_test)

[[6.7]
 [2.1]
 [8. ]
 [3.1]]


Performing StandardScaler Upon Needed Columns

In [72]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [73]:
print(x_train)

[[ 1.21 -1.   -0.51  1.43  0.21]
 [-1.75 -0.98 -1.42  0.66  0.06]
 [ 0.09  1.17  0.21  0.51  0.43]
 [ 0.8  -1.18 -0.64 -0.93  1.31]
 [ 1.31 -1.34  1.    0.71 -0.46]
 [ 0.19  0.39  0.6   1.43  1.02]
 [-1.95  1.41 -0.9  -1.42 -1.27]
 [ 1.01  0.56 -0.7   1.43  0.72]
 [-1.34 -0.67 -0.38 -0.65 -1.42]
 [-0.73  0.74  1.13  0.99  0.72]
 [ 1.11  1.51  1.39 -0.26 -0.83]
 [-0.32 -0.54 -0.51 -1.08 -0.75]
 [-0.22  0.3   1.52 -1.42 -2.01]
 [ 0.7   1.15 -1.29 -0.31  0.13]
 [-0.22 -1.42  1.45 -1.03  0.5 ]
 [ 0.09 -0.1  -0.96 -0.07  1.61]]


In [74]:
print(x_test)

[[ 2.23 -0.96  0.15  0.71  1.68]
 [-0.83  1.4  -0.31 -0.31  1.83]
 [ 2.33 -0.06  1.58 -0.74  1.31]
 [-0.22 -0.58  0.41 -1.13  0.5 ]]


Applying Linear Regression

In [94]:
from sklearn.linear_model import LinearRegression
regressor  = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression()

In [96]:
y_pred = regressor.predict(x_test)

Comparison Between Test Data & Predicted Data

In [ ]:
comparison = pd.DataFrame({'Actual': y_test.flatten(), 'Predicted': y_pred.flatten()})
print(comparison)


   Actual  Predicted
0     6.7   6.984946
1     2.1   4.033705
2     8.0   6.970720
3     3.1   4.836047


Checking The Model Efficiency Using r2_score

In [97]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)
print("R-squared Score:", r2)


R-squared Score: 0.6698238374374339
